import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>✧CAHYATI PRESS✧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="page-container">
        <header>
          <div className="container">
            <div className="title">
              Cahyati Press
            </div>
          </div>
        </header>
        <div className="coming-soon">
          <div className="about">
            <p>Cahyati Press is a publishing and printing experiment.¶
              It is an attempt at taking the pressure off of bookmaking; A long distance collaboration between
              Bali and Brisbane by two long-time friends, Avi and Kat.¶
              The press is named after Avi's late grandmother as an homage to the founders' Cirebonese roots.¶</p>
            <p>Check back soon.</p>
          </div>
        </div>
        <div className="form">
          <form action="/action_page.php">
            <label htmlFor="lname" className="label-name">Let's stay in touch:</label>
            <div className="email-input-group">
              <input type="text" className="email-input" id="lname" name="lname"
                placeholder="friend_of_cahyati@gmail.com" />
              <input type="submit" className="button" value="ENTER" />
            </div>
          </form>
        </div>
      </div>
    </div >
  )
}
